#ifndef _INTERRUPTS_H
#define _INTERRUPTS_H
#include "types.h"

#define HardwareInterruptOffset 0x20
#define PICMasterCommand 0x20
#define PICMasterData 0x21
#define PICSlaveCommand 0xA0
#define PICSlaveData 0xA1

typedef volatile struct{
    uint32 eax;
    uint32 ebx;
    uint32 ecx;
    uint32 edx;
    uint32 esi;
    uint32 edi;
    uint32 ebp;
    uint32 esp;
    uint32 error_code;
    uint32 eip;
    uint32 cs;
    uint32 eflags;
} CPUState;

typedef volatile struct
{
    int16 handlerAddressLowBits;
    uint16 gdt_codeSegmentSelector;
    uint8 reserved;
    uint8 access;
    uint16 handlerAddressHighBits;
} GateDescriptor;
typedef volatile struct{
    uint16 size;
    uint32 base;
} IDT_descriptor;

GateDescriptor IDT[256];
uint16 keyboard_event_handlers_slot;
void (*keyboard_event_handlers[16])(uint8);

void handleInterrupt(uint8 interruptnumber, CPUState currentState);
void setInterrupt(uint8 interrupt,uint16 codeSegmentSelectorOffset, void (*handler)(),uint8 DescriptorPrivilegeLevel, uint8 DescriptorType);
void setupInterrupts();
uint8 addKeyboardEvent(void (*handler)(uint8));
void removeKeyboardEvent(uint8 slot);
void keystroke_ignore(uint8 keycode);

extern void interrupts_int0();
extern void interrupts_int1();
extern void interrupts_int2();
extern void interrupts_int3();
extern void interrupts_int4();
extern void interrupts_int5();
extern void interrupts_int6();
extern void interrupts_int7();
extern void interrupts_int8();
extern void interrupts_int9();
extern void interrupts_int10();
extern void interrupts_int11();
extern void interrupts_int12();
extern void interrupts_int13();
extern void interrupts_int14();
extern void interrupts_int15();
extern void interrupts_int16();
extern void interrupts_int17();
extern void interrupts_int18();
extern void interrupts_int19();
extern void interrupts_int20();
extern void interrupts_int21();
extern void interrupts_int22();
extern void interrupts_int23();
extern void interrupts_int24();
extern void interrupts_int25();
extern void interrupts_int26();
extern void interrupts_int27();
extern void interrupts_int28();
extern void interrupts_int29();
extern void interrupts_int30();
extern void interrupts_int31();
extern void interrupts_int32();
extern void interrupts_int33();
extern void interrupts_int34();
extern void interrupts_int35();
extern void interrupts_int36();
extern void interrupts_int37();
extern void interrupts_int38();
extern void interrupts_int39();
extern void interrupts_int40();
extern void interrupts_int41();
extern void interrupts_int42();
extern void interrupts_int43();
extern void interrupts_int44();
extern void interrupts_int45();
extern void interrupts_int46();
extern void interrupts_int47();
extern void interrupts_int48();
extern void interrupts_int49();
extern void interrupts_int50();
extern void interrupts_int51();
extern void interrupts_int52();
extern void interrupts_int53();
extern void interrupts_int54();
extern void interrupts_int55();
extern void interrupts_int56();
extern void interrupts_int57();
extern void interrupts_int58();
extern void interrupts_int59();
extern void interrupts_int60();
extern void interrupts_int61();
extern void interrupts_int62();
extern void interrupts_int63();
extern void interrupts_int64();
extern void interrupts_int65();
extern void interrupts_int66();
extern void interrupts_int67();
extern void interrupts_int68();
extern void interrupts_int69();
extern void interrupts_int70();
extern void interrupts_int71();
extern void interrupts_int72();
extern void interrupts_int73();
extern void interrupts_int74();
extern void interrupts_int75();
extern void interrupts_int76();
extern void interrupts_int77();
extern void interrupts_int78();
extern void interrupts_int79();
extern void interrupts_int80();
extern void interrupts_int81();
extern void interrupts_int82();
extern void interrupts_int83();
extern void interrupts_int84();
extern void interrupts_int85();
extern void interrupts_int86();
extern void interrupts_int87();
extern void interrupts_int88();
extern void interrupts_int89();
extern void interrupts_int90();
extern void interrupts_int91();
extern void interrupts_int92();
extern void interrupts_int93();
extern void interrupts_int94();
extern void interrupts_int95();
extern void interrupts_int96();
extern void interrupts_int97();
extern void interrupts_int98();
extern void interrupts_int99();
extern void interrupts_int100();
extern void interrupts_int101();
extern void interrupts_int102();
extern void interrupts_int103();
extern void interrupts_int104();
extern void interrupts_int105();
extern void interrupts_int106();
extern void interrupts_int107();
extern void interrupts_int108();
extern void interrupts_int109();
extern void interrupts_int110();
extern void interrupts_int111();
extern void interrupts_int112();
extern void interrupts_int113();
extern void interrupts_int114();
extern void interrupts_int115();
extern void interrupts_int116();
extern void interrupts_int117();
extern void interrupts_int118();
extern void interrupts_int119();
extern void interrupts_int120();
extern void interrupts_int121();
extern void interrupts_int122();
extern void interrupts_int123();
extern void interrupts_int124();
extern void interrupts_int125();
extern void interrupts_int126();
extern void interrupts_int127();
extern void interrupts_int128();
extern void interrupts_int129();
extern void interrupts_int130();
extern void interrupts_int131();
extern void interrupts_int132();
extern void interrupts_int133();
extern void interrupts_int134();
extern void interrupts_int135();
extern void interrupts_int136();
extern void interrupts_int137();
extern void interrupts_int138();
extern void interrupts_int139();
extern void interrupts_int140();
extern void interrupts_int141();
extern void interrupts_int142();
extern void interrupts_int143();
extern void interrupts_int144();
extern void interrupts_int145();
extern void interrupts_int146();
extern void interrupts_int147();
extern void interrupts_int148();
extern void interrupts_int149();
extern void interrupts_int150();
extern void interrupts_int151();
extern void interrupts_int152();
extern void interrupts_int153();
extern void interrupts_int154();
extern void interrupts_int155();
extern void interrupts_int156();
extern void interrupts_int157();
extern void interrupts_int158();
extern void interrupts_int159();
extern void interrupts_int160();
extern void interrupts_int161();
extern void interrupts_int162();
extern void interrupts_int163();
extern void interrupts_int164();
extern void interrupts_int165();
extern void interrupts_int166();
extern void interrupts_int167();
extern void interrupts_int168();
extern void interrupts_int169();
extern void interrupts_int170();
extern void interrupts_int171();
extern void interrupts_int172();
extern void interrupts_int173();
extern void interrupts_int174();
extern void interrupts_int175();
extern void interrupts_int176();
extern void interrupts_int177();
extern void interrupts_int178();
extern void interrupts_int179();
extern void interrupts_int180();
extern void interrupts_int181();
extern void interrupts_int182();
extern void interrupts_int183();
extern void interrupts_int184();
extern void interrupts_int185();
extern void interrupts_int186();
extern void interrupts_int187();
extern void interrupts_int188();
extern void interrupts_int189();
extern void interrupts_int190();
extern void interrupts_int191();
extern void interrupts_int192();
extern void interrupts_int193();
extern void interrupts_int194();
extern void interrupts_int195();
extern void interrupts_int196();
extern void interrupts_int197();
extern void interrupts_int198();
extern void interrupts_int199();
extern void interrupts_int200();
extern void interrupts_int201();
extern void interrupts_int202();
extern void interrupts_int203();
extern void interrupts_int204();
extern void interrupts_int205();
extern void interrupts_int206();
extern void interrupts_int207();
extern void interrupts_int208();
extern void interrupts_int209();
extern void interrupts_int210();
extern void interrupts_int211();
extern void interrupts_int212();
extern void interrupts_int213();
extern void interrupts_int214();
extern void interrupts_int215();
extern void interrupts_int216();
extern void interrupts_int217();
extern void interrupts_int218();
extern void interrupts_int219();
extern void interrupts_int220();
extern void interrupts_int221();
extern void interrupts_int222();
extern void interrupts_int223();
extern void interrupts_int224();
extern void interrupts_int225();
extern void interrupts_int226();
extern void interrupts_int227();
extern void interrupts_int228();
extern void interrupts_int229();
extern void interrupts_int230();
extern void interrupts_int231();
extern void interrupts_int232();
extern void interrupts_int233();
extern void interrupts_int234();
extern void interrupts_int235();
extern void interrupts_int236();
extern void interrupts_int237();
extern void interrupts_int238();
extern void interrupts_int239();
extern void interrupts_int240();
extern void interrupts_int241();
extern void interrupts_int242();
extern void interrupts_int243();
extern void interrupts_int244();
extern void interrupts_int245();
extern void interrupts_int246();
extern void interrupts_int247();
extern void interrupts_int248();
extern void interrupts_int249();
extern void interrupts_int250();
extern void interrupts_int251();
extern void interrupts_int252();
extern void interrupts_int253();
extern void interrupts_int254();
extern void interrupts_int255();

#endif